local c = require('florence.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- highlights
  hl(0, "Normal", { fg = c.base05, bg = c.base00, })
  hl(0, "SignColumn", { fg = 'NONE', bg = c.base00, })
  hl(0, "MsgArea", { fg = c.base05, bg = c.base00, })
  hl(0, "ModeMsg", { fg = c.base05, bg = c.base00, })
  hl(0, "MsgSeparator", { fg = c.base05, bg = c.base00, })
  hl(0, "SpellCap", { fg = c.base08, bg = 'NONE', underline=true, })
  hl(0, "SpellLocal", { fg = c.r3d, bg = 'NONE', underline=true, })
  hl(0, "SpellRare", { fg = c.r3d, bg = 'NONE', underline=true, })
  hl(0, "NormalNC", { fg = c.base05, bg = c.base00, })
  hl(0, "Pmenu", { fg = c.base06, bg = c.base01, blend = 50, })
  hl(0, "PmenuSel", { fg = 'NONE', bg = c.base08, })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = c.base01, })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c.base07, })
  hl(0, "WildMenu", { fg = c.base05, bg = c.base0A, })
  hl(0, "CursorLineNr", { fg = c.base09, bg = 'NONE', bold=true, })
  hl(0, "Comment", { fg = c.base03, bg = 'NONE', italic=true, })
  hl(0, "Folded", { fg = c.base06, bg = c.base01, })
  hl(0, "FoldColumn", { fg = c.base06, bg = c.base01, })
  hl(0, "LineNr", { fg = c.base03, bg = 'NONE', })
  hl(0, "FloatBorder", { fg = c.base04, bg = 'NONE', })
  hl(0, "Whitespace", { fg = c.base00, bg = 'NONE', })
  hl(0, "VertSplit", { fg = c.base06, bg = c.base00, })
  hl(0, "CursorLine", { fg = 'NONE', bg = c.base01, })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.base01, })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.base01, })
  hl(0, "NormalFloat", { fg = 'NONE', bg = c.base01, })
  hl(0, "Visual", { fg = 'NONE', bg = c.base02, })
  hl(0, "DiffAdd", { fg = c.base05, bg = c.r3d, })
  hl(0, "DiffChange", { fg = c.base05, bg = c.r3d, underline=true, })
  hl(0, "DiffDelete", { fg = c.base05, bg = c.r3d, })
  hl(0, "QuickFixLine", { fg = 'NONE', bg = c.base0A, })
  hl(0, "MatchWord", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParen", { fg = c.r3d, bg = c.base00, underline=true, })
  hl(0, "MatchWordCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParenCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Cursor", { fg = c.base04, bg = c.base07, })
  hl(0, "lCursor", { link = 'Cursor' })
  hl(0, "CursorIM", { link = 'Cursor' })
  hl(0, "TermCursor", { link = 'Cursor' })
  hl(0, "TermCursorNC", { link = 'Cursor' })
  hl(0, "Conceal", { fg = c.base06, bg = 'NONE', })
  hl(0, "Directory", { fg = c.r3d, bg = 'NONE', })
  hl(0, "SpecialKey", { fg = c.r3d, bg = 'NONE', bold=true, })
  hl(0, "Title", { fg = c.base09, bg = 'NONE', bold=true, })
  hl(0, "ErrorMsg", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "Search", { fg = c.base04, bg = c.base0A, })
  hl(0, "IncSearch", { fg = c.base04, bg = c.base0A, })
  hl(0, "Substitute", { fg = c.base06, bg = c.r3d, })
  hl(0, "MoreMsg", { fg = c.r3d, bg = 'NONE', })
  hl(0, "Question", { fg = c.r3d, bg = 'NONE', })
  hl(0, "EndOfBuffer", { fg = 'NONE', bg = 'NONE', })
  hl(0, "NonText", { fg = c.base00, bg = c.base00, })
  hl(0, "Variable", { fg = c.base05, bg = 'NONE', })
  hl(0, "String", { fg = c.base0B, bg = 'NONE', })
  hl(0, "Character", { fg = c.base0C, bg = 'NONE', })
  hl(0, "Constant", { fg = c.base05, bg = 'NONE', bold=true, })
  hl(0, "Number", { fg = c.base09, bg = 'NONE', })
  hl(0, "Boolean", { fg = c.base09, bg = 'NONE', bold=true, })
  hl(0, "Float", { link = 'Number' })
  hl(0, "Identifier", { fg = c.base05, bg = 'NONE', })
  hl(0, "Function", { fg = c.base0D, bg = 'NONE', })
  hl(0, "Operator", { fg = c.base0F, bg = 'NONE', })
  hl(0, "Type", { fg = c.base0A, bg = 'NONE', })
  hl(0, "StorageClass", { fg = c.r3d, bg = 'NONE', })
  hl(0, "Structure", { link = 'Type' })
  hl(0, "Typedef", { fg = c.base0F, bg = 'NONE', })
  hl(0, "Keyword", { fg = c.base0E, bg = 'NONE', })
  hl(0, "Statement", { fg = c.base0E, bg = 'NONE', })
  hl(0, "Conditional", { fg = c.base0A, bg = 'NONE', })
  hl(0, "Repeat", { fg = c.base0A, bg = 'NONE', })
  hl(0, "Label", { fg = c.base0C, bg = 'NONE', })
  hl(0, "Exception", { link = 'Keyword' })
  hl(0, "Include", { link = 'Keyword' })
  hl(0, "PreProc", { link = 'Tag' })
  hl(0, "Define", { link = 'Keyword' })
  hl(0, "Macro", { link = 'Function' })
  hl(0, "PreCondit", { fg = c.r3d, bg = 'NONE', })
  hl(0, "Special", { fg = c.base04, bg = 'NONE', })
  hl(0, "SpecialChar", { fg = c.base0C, bg = 'NONE', })
  hl(0, "Tag", { fg = c.base08, bg = 'NONE', })
  hl(0, "Debug", { fg = c.r3d, bg = 'NONE', })
  hl(0, "Delimiter", { fg = c.base04, bg = 'NONE', })
  hl(0, "SpecialComment", { link = 'Comment' })
  hl(0, "Underlined", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Bold", { fg = 'NONE', bg = 'NONE', bold=true, })
  hl(0, "Italic", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "Ignore", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "Todo", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "Error", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "TabLine", { fg = c.base06, bg = c.r3d, })
  hl(0, "TabLineSel", { fg = 'NONE', bg = c.r3d, })
  hl(0, "TabLineFill", { fg = c.r3d, bg = c.r3d, })

  -- Treesitter
  hl(0, "TSComment", { link = 'Comment' })
  hl(0, "TSAnnotation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSAttribute", { fg = c.base0F, bg = 'NONE', })
  hl(0, "TSConstructor", { link = 'Keyword' })
  hl(0, "TSType", { link = 'Type' })
  hl(0, "TSTypeBuiltin", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSConditional", { link = 'Conditional' })
  hl(0, "TSException", { link = 'Exception' })
  hl(0, "TSInclude", { link = 'Include' })
  hl(0, "TSKeywordReturn", { link = 'Keyword' })
  hl(0, "TSKeyword", { link = 'Keyword' })
  hl(0, "TSKeywordFunction", { link = 'Function' })
  hl(0, "TSLabel", { link = 'Label' })
  hl(0, "TSNamespace", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSRepeat", { link = 'repeat' })
  hl(0, "TSConstant", { link = 'Constant' })
  hl(0, "TSConstBuiltin", { link = 'Constant' })
  hl(0, "TSFloat", { link = 'Float' })
  hl(0, "TSNumber", { link = 'Number' })
  hl(0, "TSBoolean", { link = 'Boolean' })
  hl(0, "TSCharacter", { link = 'Character' })
  hl(0, "TSError", { link = 'Error' })
  hl(0, "TSFunction", { link = 'Function' })
  hl(0, "TSFuncBuiltin", { link = 'Function' })
  hl(0, "TSMethod", { fg = c.base0D, bg = 'NONE', })
  hl(0, "TSConstMacro", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSFuncMacro", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSVariable", { link = 'Variable' })
  hl(0, "TSVariableBuiltin", { fg = c.base09, bg = 'NONE', })
  hl(0, "TSProperty", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSField", { fg = c.base05, bg = 'NONE', })
  hl(0, "TSParameter", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSParameterReference", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSSymbol", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSText", { fg = c.base05, bg = 'NONE', })
  hl(0, "TSOperator", { link = 'Operator' })
  hl(0, "TSPunctDelimiter", { link = 'Delimiter' })
  hl(0, "TSTagDelimiter", { link = 'Delimiter' })
  hl(0, "TSTagAttribute", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSPunctBracket", { fg = c.base04, bg = 'NONE', })
  hl(0, "TSPunctSpecial", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSString", { link = 'String' })
  hl(0, "TSStringRegex", { fg = c.base0C, bg = 'NONE', })
  hl(0, "TSStringEscape", { fg = c.r3d, bg = 'NONE', bold=true, })
  hl(0, "TSTag", { link = 'Tag' })
  hl(0, "TSEmphasis", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "TSUnderline", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "TSTitle", { link = 'Title' })
  hl(0, "TSLiteral", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TSURI", { fg = c.r3d, bg = 'NONE', underline=true, })
  hl(0, "TSKeywordOperator", { link = 'Keyword' })
  hl(0, "TSStructure", { link = 'Structure' })
  hl(0, "TSStrong", { fg = c.r3d, bg = 'NONE', bold=true, })
  hl(0, "TSQueryLinterError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "TreesitterContext", { fg = 'NONE', bg = c.base01, })

  -- markdown
  hl(0, "markdownBlockquote", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownCode", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownCodeBlock", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownCodeDelimiter", { link = 'Delimiter' })
  hl(0, "markdownH1", { fg = c.base0D, bg = 'NONE', })
  hl(0, "markdownH3", { fg = c.base0D, bg = 'NONE', })
  hl(0, "markdownH4", { fg = c.base0D, bg = 'NONE', })
  hl(0, "markdownH5", { fg = c.base0D, bg = 'NONE', })
  hl(0, "markdownH6", { fg = c.base0D, bg = 'NONE', })
  hl(0, "markdownHeadingDelimiter", { link = 'Delimiter' })
  hl(0, "markdownHeadingRule", { fg = c.base05, bg = 'NONE', bold=true, })
  hl(0, "markdownId", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownIdDeclaration", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownIdDelimiter", { link = 'Delimiter' })
  hl(0, "markdownLinkDelimiter", { link = 'Delimiter' })
  hl(0, "markdownBold", { fg = c.base0E, bg = 'NONE', bold=true, })
  hl(0, "markdownItalic", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "markdownBoldItalic", { fg = c.base0E, bg = 'NONE', italic=true, bold=true, })
  hl(0, "markdownListMarker", { fg = c.base06, bg = 'NONE', })
  hl(0, "markdownOrderedListMarker", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownRule", { fg = c.base06, bg = 'NONE', })
  hl(0, "markdownUrl", { fg = c.r3d, bg = 'NONE', underline=true, })
  hl(0, "markdownLinkText", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownFootnote", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownFootnoteDefinition", { fg = c.r3d, bg = 'NONE', })
  hl(0, "markdownEscape", { fg = c.base08, bg = 'NONE', })

  -- Whichkey
  hl(0, "WhichKey", { fg = c.r3d, bg = 'NONE', })
  hl(0, "WhichKeySeperator", { fg = c.r3d, bg = 'NONE', })
  hl(0, "WhichKeyGroup", { fg = c.r3d, bg = 'NONE', })
  hl(0, "WhichKeyDesc", { fg = c.r3d, bg = 'NONE', })
  hl(0, "WhichKeyFloat", { fg = 'NONE', bg = c.base01, })

  -- Git
  hl(0, "SignAdd", { fg = c.r3d, bg = 'NONE', })
  hl(0, "SignChange", { fg = c.r3d, bg = 'NONE', })
  hl(0, "SignDelete", { fg = c.r3d, bg = 'NONE', })
  hl(0, "GitSignsAdd", { fg = c.r3d, bg = 'NONE', })
  hl(0, "GitSignsChange", { fg = c.r3d, bg = 'NONE', })
  hl(0, "GitSignsDelete", { fg = c.r3d, bg = 'NONE', })

  -- LSP
  hl(0, "LspDiagnosticsDefaultError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsDefaultWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsDefaultInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsDefaultInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsDefaultHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsVirtualTextError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsVirtualTextWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsVirtualTextInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsVirtualTextInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsVirtualTextHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsFloatingError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsFloatingWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsFloatingInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsFloatingInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsFloatingHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignWarn", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticSignHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticFloatingError", { fg = c.r3d, bg = c.base01, })
  hl(0, "DiagnosticFloatingWarn", { fg = c.r3d, bg = c.base01, })
  hl(0, "DiagnosticFloatingInfo", { fg = c.r3d, bg = c.base01, })
  hl(0, "DiagnosticFloatingHint", { fg = c.r3d, bg = c.base01, })
  hl(0, "DiagnosticError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticWarn", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticVirtualTextError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticVirtualTextWarn", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticVirtualTextInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticVirtualTextHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "DiagnosticUnderlineError", { fg = 'NONE', bg = 'NONE', sp = c.r3d, undercurl=true, })
  hl(0, "DiagnosticUnderlineWarn", { fg = 'NONE', bg = 'NONE', sp = c.r3d, undercurl=true, })
  hl(0, "DiagnosticUnderlineInfo", { fg = 'NONE', bg = 'NONE', sp = c.r3d, undercurl=true, })
  hl(0, "DiagnosticUnderlineHint", { fg = 'NONE', bg = 'NONE', sp = c.r3d, undercurl=true, })
  hl(0, "LspDiagnosticsSignError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsSignWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsSignInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsSignInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsSignHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsError", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsWarning", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsInformation", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsInfo", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspDiagnosticsHint", { fg = c.r3d, bg = 'NONE', })
  hl(0, "LspReferenceRead", { fg = 'NONE', bg = '#2e303b', })
  hl(0, "LspReferenceText", { fg = 'NONE', bg = '#2e303b', })
  hl(0, "LspReferenceWrite", { fg = 'NONE', bg = '#2e303b', })
  hl(0, "LspCodeLens", { fg = c.r3d, bg = 'NONE', italic=true, })
  hl(0, "LspCodeLensSeparator", { fg = c.r3d, bg = 'NONE', italic=true, })

  -- Telescope
  hl(0, "TelescopeSelection", { fg = c.base08, bg = 'NONE', })
  hl(0, "TelescopeMatching", { fg = c.base0C, bg = 'NONE', bold=true, })
  hl(0, "TelescopeBorder", { fg = c.base05, bg = 'NONE', })

  -- NvimTree
  hl(0, "NvimTreeFolderIcon", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeIndentMarker", { fg = c.r3d, bg = c.base01, })
  hl(0, "NvimTreeNormal", { fg = c.base05, bg = c.base01, })
  hl(0, "NvimTreeVertSplit", { fg = c.base00, bg = c.base00, })
  hl(0, "WinSeparator", { fg = c.base00, bg = c.base00, })
  hl(0, "NvimTreeFolderName", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeOpenedFolderName", { fg = c.r3d, bg = 'NONE', italic=true, bold=true, })
  hl(0, "NvimTreeEmptyFolderName", { fg = c.r3d, bg = 'NONE', italic=true, })
  hl(0, "NvimTreeGitIgnored", { fg = c.r3d, bg = 'NONE', italic=true, })
  hl(0, "NvimTreeImageFile", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeSpecialFile", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeEndOfBuffer", { fg = c.base01, bg = c.base01, })
  hl(0, "NvimTreeCursorLine", { fg = 'NONE', bg = c.r3d, })
  hl(0, "NvimTreeGitignoreIcon", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitStaged", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitNew", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitRenamed", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitDeleted", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitMerge", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeGitDirty", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeSymlink", { fg = c.r3d, bg = 'NONE', })
  hl(0, "NvimTreeRootFolder", { fg = c.base05, bg = 'NONE', bold=true, })
  hl(0, "NvimTreeExecFile", { fg = '#9fba89', bg = 'NONE', })
  hl(0, "NvimTreeTitle", { fg = c.base05, bg = c.base00, italic=true, bold=true, })

  -- Buffer
  hl(0, "BufferCurrent", { fg = c.base05, bg = c.base00, })
  hl(0, "BufferCurrentIndex", { fg = c.base05, bg = c.base00, })
  hl(0, "BufferCurrentMod", { fg = c.r3d, bg = c.base00, })
  hl(0, "BufferCurrentSign", { fg = c.r3d, bg = c.base00, })
  hl(0, "BufferCurrentTarget", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "BufferVisible", { fg = c.base05, bg = c.base00, })
  hl(0, "BufferVisibleIndex", { fg = c.base05, bg = c.base00, })
  hl(0, "BufferVisibleMod", { fg = c.r3d, bg = c.base00, })
  hl(0, "BufferVisibleSign", { fg = c.r3d, bg = c.base00, })
  hl(0, "BufferVisibleTarget", { fg = c.r3d, bg = c.base00, bold=true, })
  hl(0, "BufferInactive", { fg = c.r3d, bg = c.base01, })
  hl(0, "BufferInactiveIndex", { fg = c.r3d, bg = c.base01, })
  hl(0, "BufferInactiveMod", { fg = c.r3d, bg = c.base01, })
  hl(0, "BufferInactiveSign", { fg = c.r3d, bg = c.base01, })
  hl(0, "BufferInactiveTarget", { fg = c.r3d, bg = c.base01, bold=true, })

  -- IndentBlankline
  hl(0, "IndentBlanklineContextChar", { fg = c.base03, bg = 'NONE', })
  hl(0, "IndentBlanklineContextStart", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "IndentBlanklineChar", { fg = c.base03, bg = 'NONE', })
  hl(0, "IndentBlanklineSpaceChar", { fg = c.base03, bg = 'NONE', })
  hl(0, "IndentBlanklineSpaceCharBlankline", { fg = c.base03, bg = 'NONE', })

  -- Cmp
  hl(0, "CmpItemAbbrDeprecated", { fg = c.base0F, bg = 'NONE', strikethrough=true, })
  hl(0, "CmpItemAbbrMatch", { fg = c.base0C, bg = 'NONE', })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.base0C, bg = 'NONE', })
  hl(0, "CmpItemKindFunction", { link = 'Function' })
  hl(0, "CmpItemKindMethod", { link = 'TSMethod' })
  hl(0, "CmpItemKindConstructor", { link = 'TSConstructor' })
  hl(0, "CmpItemKindClass", { link = 'Type' })
  hl(0, "CmpItemKindEnum", { link = 'Type' })
  hl(0, "CmpItemKindEvent", { fg = c.base05, bg = 'NONE', })
  hl(0, "CmpItemKindInterface", { link = 'Type' })
  hl(0, "CmpItemKindStruct", { link = 'Structure' })
  hl(0, "CmpItemKindVariable", { link = 'Variable' })
  hl(0, "CmpItemKindField", { link = 'TSField' })
  hl(0, "CmpItemKindProperty", { link = 'TSProperty' })
  hl(0, "CmpItemKindEnumMember", { fg = c.r3d, bg = 'NONE', })
  hl(0, "CmpItemKindConstant", { link = 'Constant' })
  hl(0, "CmpItemKindKeyword", { link = 'Keyword' })
  hl(0, "CmpItemKindModule", { fg = c.r3d, bg = 'NONE', })
  hl(0, "CmpItemKindValue", { link = 'Number' })
  hl(0, "CmpItemKindUnit", { fg = c.base05, bg = 'NONE', })
  hl(0, "CmpItemKindText", { link = 'TSText' })
  hl(0, "CmpItemKindSnippet", { fg = c.base08, bg = 'NONE', })
  hl(0, "CmpItemKindFile", { fg = c.r3d, bg = 'NONE', })
  hl(0, "CmpItemKindFolder", { fg = c.base05, bg = 'NONE', })
  hl(0, "CmpItemKindColor", { fg = c.base05, bg = 'NONE', })
  hl(0, "CmpItemKindReference", { fg = c.r3d, bg = 'NONE', })
  hl(0, "CmpItemKindOperator", { link = 'Operator' })
  hl(0, "CmpItemKindTypeParameter", { link = 'TSParameter' })

  -- Custom
  hl(0, "@type.java", { link = 'Function' })
  hl(0, "@parameter.doxygen", { link = 'Function' })
  hl(0, "@attribute", { link = 'TSAttribute' })
  hl(0, "@function.builtin", { link = 'TSFuncBuiltin' })
  hl(0, "@tag.delimiter", { link = 'Delimiter' })
  hl(0, "@type.qualifier", { link = 'Keyword' })
  hl(0, "@constructor", { link = 'TSConstructor' })
  hl(0, "@variable.builtin", { link = 'TSVariableBuiltin' })
  hl(0, "@label.json", { link = 'Identifier' })
  hl(0, "@text.literal.ledger", { link = 'Identifier' })

end

return theme