[information]
 name = "florence"
 background = "dark"
 author = 'Felipe Nakamoto <felipe.ymn@gmail.com>'

[palette]
 base00 = "#101317" # default background
 base01 = "#1a1d21" # lighter background
 base02 = "#23262a" # selection background
 # base03 = "#2b2e32" # comments, invisibles, line highlighting
 base03 = "#383B3F" # comments, invisibles, line highlighting
 base04 = "#57606b" # dark foreground (used for status bars), delimiters
 base05 = "#c5c5c6" # variables, fields, default foreground, caret, operators, constant (bold)
 base06 = "#cbcbcc" # light foreground (not often used)
 base07 = "#d4d4d5" # light background (not often used)
 base08 = "#d4ae5c" # xml tags, markup link text, markup lists, diff deleted
 base09 = "#78beab" # titles, integers, boolean, xml attributes, markup link url
 base0A = "#e5d487" # classes, search text background, repeat, type, 
 base0B = "#9BB02E" # strings, inherited class, markup code, diff inserted
 base0C = "#ffa4cb" # support, regular expressions, escape characters, markup quotes, fuzzy match
 base0D = "#d9573d" # functions, methods, attribute ids, headings
 base0E = "#e69147" # keywords, storage, selector, markup, italic, diff changed, markdown bold
 base0F = "#50799e" # deprecated, opening/closing embedded language tags, e.g

 r3d = "#FF0000"

 # fg = '#f5f5f5'
 # bg = '#0c0e0f'
 # alt_fg = '#f5f5f5'
 # dark = '#14171a'

 # search_blue = '#083C5A'
 # indent_blankline = '#202020'
 # gray = '#404040'
 # light_gray = '#d9d9d9'
 # blue = '#9FCDD9'
 # light_blue = '#E0FCF2'
 # cyan = '#78BEAB'
 # green = '#9BB02E'
 # red = '#D9573D' 
 # light_red = '#FFA4CB'
 # purple = '#bd658a'
 # yellow = '#d4ae5c'
 # magenta = '#59223C'
 # orange = '#e68147'

 # sign_add = '#3eb05a'
 # sign_change = '#B09435'
 # sign_delete = '#B02C34'

 # error_red = '#b14f56'
 # error_yellow = '#ab8b46'
 # info_blue = '#286180'
 # info_cyan = '#78beab'

 # fuzzy_match = '#A3E27C'

[highlights]
 Normal = 'base05 base00'
 SignColumn = '- base00'
 MsgArea = 'base05 base00'
 ModeMsg = 'base05 base00'
 MsgSeparator = 'base05 base00'
 SpellCap = 'base08 - u'
 SpellLocal = 'r3d - u'
 SpellRare = 'r3d - u'
 NormalNC = 'base05 base00'
 Pmenu = 'base06 base01 - - 50'
 PmenuSel = '- base08'
 PmenuSbar = '- base01'
 PmenuThumb = '- base07'

 WildMenu = 'base05 base0A'
 CursorLineNr = 'base09 - b'
 Comment = 'base03 - i'
 Folded = 'base06 base01'
 FoldColumn = 'base06 base01'
 LineNr = 'base03 -'
 FloatBorder = 'base04'
 Whitespace = 'base00 -'
 VertSplit = 'base06 base00'
 CursorLine = '- base01'
 CursorColumn = '- base01'
 ColorColumn = '- base01'
 NormalFloat = '- base01'
 Visual = '- base02'
 DiffAdd = 'base05 r3d'
 DiffChange = 'base05 r3d u'
 DiffDelete = 'base05 r3d'
 QuickFixLine = '- base0A'
 MatchWord = '- - u'
 MatchParen = 'r3d base00 u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'base04 base07'
 lCursor = 'link:Cursor'
 CursorIM = 'link:Cursor'
 TermCursor = 'link:Cursor'
 TermCursorNC = 'link:Cursor'
 Conceal = 'base06'
 Directory = 'r3d'
 SpecialKey = 'r3d - b'
 Title = 'base09 - b'
 ErrorMsg = 'r3d base00 b'
 Search = 'base04 base0A'
 IncSearch = 'base04 base0A'
 Substitute = 'base06 r3d'
 MoreMsg = 'r3d'
 Question = 'r3d'
 EndOfBuffer = '- -'
 NonText = 'base00 base00'
 Variable = 'base05'
 String = 'base0B'
 Character = 'base0C'
 Constant = 'base05 - b'
 Number = 'base09'
 Boolean = 'base09 - b'
 Float = 'link:Number'
 Identifier = 'base05'
 Function = 'base0D'
 Operator = 'base0F'
 Type = 'base0A'
 StorageClass = 'r3d'
 Structure = 'link:Type'
 Typedef = 'base0F'
 Keyword = 'base0E'
 Statement = 'base0E'
 Conditional = 'base0A'
 Repeat = 'base0A'
 Label = 'base0C'
 Exception = 'link:Keyword'
 Include = 'link:Keyword'
 PreProc = 'link:Tag'
 Define = 'link:Keyword'
 Macro = 'link:Function'
 PreCondit = 'r3d'
 Special = 'base04'
 SpecialChar = 'base0C'
 Tag = 'base08'
 Debug = 'r3d'
 Delimiter = 'base04 -'
 SpecialComment = 'link:Comment'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'r3d base00 b'
 Todo = 'r3d base00 b'
 Error = 'r3d base00 b'
 TabLine = 'base06 r3d'
 TabLineSel = '- r3d'
 TabLineFill = 'r3d r3d'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'r3d'
 TSAttribute = 'base0F'
 TSConstructor = 'link:Keyword'
 TSType = 'link:Type'
 TSTypeBuiltin = 'r3d'
 TSConditional = 'link:Conditional'
 TSException = 'link:Exception'
 TSInclude = 'link:Include'
 TSKeywordReturn = 'link:Keyword'
 TSKeyword = 'link:Keyword'
 TSKeywordFunction = 'link:Function'
 TSLabel = 'link:Label'
 TSNamespace = 'r3d'
 TSRepeat = 'link:repeat'
 TSConstant = 'link:Constant'
 TSConstBuiltin = 'link:Constant'
 TSFloat = 'link:Float'
 TSNumber = 'link:Number'
 TSBoolean = 'link:Boolean'
 TSCharacter = 'link:Character'
 TSError = 'link:Error'
 TSFunction = 'link:Function'
 TSFuncBuiltin = 'link:Function'
 TSMethod = 'base0D'
 TSConstMacro = 'r3d'
 TSFuncMacro = 'r3d'
 TSVariable = 'link:Variable'
 TSVariableBuiltin = 'base09'
 TSProperty = 'r3d'
 TSField = 'base05'
 TSParameter = 'r3d'
 TSParameterReference = 'r3d'
 TSSymbol = 'r3d'
 TSText = 'base05'
 TSOperator = 'link:Operator'
 TSPunctDelimiter = 'link:Delimiter'
 TSTagDelimiter = 'link:Delimiter'
 TSTagAttribute = 'r3d'
 TSPunctBracket = 'base04 -'
 TSPunctSpecial = 'r3d'
 TSString = 'link:String'
 TSStringRegex = 'base0C'
 TSStringEscape = 'r3d - b'
 TSTag = 'link:Tag'
 TSEmphasis = '- - i'
 TSUnderline = '- - u'
 TSTitle = 'link:Title'
 TSLiteral = 'r3d'
 TSURI = 'r3d - u'
 TSKeywordOperator = 'link:Keyword'
 TSStructure = 'link:Structure'
 TSStrong = 'r3d - b'
 TSQueryLinterError = 'r3d'
 TreesitterContext = '- base01'

[markdown]
 markdownBlockquote = 'r3d'
 markdownCode = 'r3d'
 markdownCodeBlock = 'r3d'
 markdownCodeDelimiter = 'link:Delimiter'
 markdownH1 = 'base0D'
 markdownH3 = 'base0D'
 markdownH4 = 'base0D'
 markdownH5 = 'base0D'
 markdownH6 = 'base0D'
 markdownHeadingDelimiter = 'link:Delimiter'
 markdownHeadingRule = 'base05 - b'
 markdownId = 'r3d'
 markdownIdDeclaration = 'r3d'
 markdownIdDelimiter = 'link:Delimiter'
 markdownLinkDelimiter = 'link:Delimiter'
 markdownBold = 'base0E - b'
 markdownItalic = '- - i'
 markdownBoldItalic = 'base0E - bi'
 markdownListMarker = 'base06'
 markdownOrderedListMarker = 'r3d'
 markdownRule = 'base06'
 markdownUrl = 'r3d - u'
 markdownLinkText = 'r3d'
 markdownFootnote = 'r3d'
 markdownFootnoteDefinition = 'r3d'
 markdownEscape = 'base08'

[Whichkey]
 WhichKey = 'r3d'
 WhichKeySeperator = 'r3d'
 WhichKeyGroup = 'r3d'
 WhichKeyDesc = 'r3d'
 WhichKeyFloat = '- base01'

[Git]
 # Testing
 SignAdd = 'base0B'
 SignChange = 'r3d'
 SignDelete = 'base0D'
 GitSignsAdd = 'base0B'
 GitSignsChange = 'r3d'
 GitSignsDelete = 'base0D'

[LSP]
 LspDiagnosticsDefaultError = 'r3d'
 LspDiagnosticsDefaultWarning = 'r3d'
 LspDiagnosticsDefaultInformation = 'r3d'
 LspDiagnosticsDefaultInfo = 'r3d'
 LspDiagnosticsDefaultHint = 'r3d'
 LspDiagnosticsVirtualTextError = 'r3d'
 LspDiagnosticsVirtualTextWarning = 'r3d'
 LspDiagnosticsVirtualTextInformation = 'r3d'
 LspDiagnosticsVirtualTextInfo = 'r3d'
 LspDiagnosticsVirtualTextHint = 'r3d'
 LspDiagnosticsFloatingError = 'r3d'
 LspDiagnosticsFloatingWarning = 'r3d'
 LspDiagnosticsFloatingInformation = 'r3d'
 LspDiagnosticsFloatingInfo = 'r3d'
 LspDiagnosticsFloatingHint = 'r3d'

 DiagnosticSignError = 'r3d'
 DiagnosticSignWarning = 'r3d'
 DiagnosticSignWarn = 'r3d'
 DiagnosticSignInformation = 'r3d'
 DiagnosticSignInfo = 'r3d'
 DiagnosticSignHint = 'r3d'
#Test
 DiagnosticFloatingError = 'r3d base01'
 DiagnosticFloatingWarn = 'r3d base01'
 DiagnosticFloatingInfo = 'r3d base01'
 DiagnosticFloatingHint = 'r3d base01'

 DiagnosticError = 'r3d'
 DiagnosticWarn = 'r3d'
 DiagnosticInfo = 'r3d'
 DiagnosticHint = 'r3d'

 DiagnosticVirtualTextError = 'r3d'
 DiagnosticVirtualTextWarn = 'r3d'
 DiagnosticVirtualTextInfo  = 'r3d'
 DiagnosticVirtualTextHint = 'r3d'

 DiagnosticUnderlineError= '- - c r3d'
 DiagnosticUnderlineWarn= '- - c r3d'
 DiagnosticUnderlineInfo= '- - c r3d'
 DiagnosticUnderlineHint= '- - c r3d'


 LspDiagnosticsSignError = 'r3d'
 LspDiagnosticsSignWarning = 'r3d'
 LspDiagnosticsSignInformation = 'r3d'
 LspDiagnosticsSignInfo = 'r3d'
 LspDiagnosticsSignHint = 'r3d'

 LspDiagnosticsError = 'r3d'
 LspDiagnosticsWarning = 'r3d'
 LspDiagnosticsInformation = 'r3d'
 LspDiagnosticsInfo = 'r3d'
 LspDiagnosticsHint = 'r3d'
 # LspDiagnosticsUnderlineError = 'r3d r3d u'
 # LspDiagnosticsUnderlineWarning = 'r3d r3d u'
 # LspDiagnosticsUnderlineInformation = 'r3d r3d u'
 # LspDiagnosticsUnderlineInfo = '- - u'
 # LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- #2e303b'
 LspReferenceText = '- #2e303b'
 LspReferenceWrite = '- #2e303b'
 LspCodeLens = 'r3d - i'
 LspCodeLensSeparator = 'r3d - i'

[Telescope] 
 TelescopeSelection = 'base08'
 TelescopeMatching = 'base0C - b'
 TelescopeBorder = 'base05'

[NvimTree]
 NvimTreeFolderIcon = 'r3d'
 NvimTreeIndentMarker = 'r3d base01'
 NvimTreeNormal = 'base05 base01'
 NvimTreeVertSplit = 'base00 base00'
 WinSeparator = 'base00 base00'
 NvimTreeFolderName = 'r3d'
 NvimTreeOpenedFolderName = 'r3d - bi'
 NvimTreeEmptyFolderName = 'r3d - i'
 NvimTreeGitIgnored = 'r3d - i'
 NvimTreeImageFile = 'r3d'
 NvimTreeSpecialFile = 'r3d'
 NvimTreeEndOfBuffer = 'base01 base01'
 NvimTreeCursorLine = '- r3d'
 NvimTreeGitignoreIcon = 'r3d'
 NvimTreeGitStaged = 'r3d'
 NvimTreeGitNew = 'r3d'
 NvimTreeGitRenamed = 'r3d'
 NvimTreeGitDeleted = 'r3d'
 NvimTreeGitMerge = 'r3d'
 NvimTreeGitDirty = 'r3d'

 NvimTreeSymlink = 'r3d'
 NvimTreeRootFolder = 'base05 - b'
 NvimTreeExecFile = '#9FBA89'
# Custom highlight group for NvimTree Title
 NvimTreeTitle = 'base05 base00 bi'

[Buffer]
 BufferCurrent = 'base05 base00'
 BufferCurrentIndex = 'base05 base00'
 BufferCurrentMod = 'r3d base00'
 BufferCurrentSign = 'r3d base00'
 BufferCurrentTarget = 'r3d base00 b'

 BufferVisible = 'base05 base00'
 BufferVisibleIndex = 'base05 base00'
 BufferVisibleMod = 'r3d base00'
 BufferVisibleSign = 'r3d base00'
 BufferVisibleTarget = 'r3d base00 b'

 BufferInactive = 'r3d base01'
 BufferInactiveIndex = 'r3d base01'
 BufferInactiveMod = 'r3d base01'
 BufferInactiveSign = 'r3d base01'
 BufferInactiveTarget = 'r3d base01 b'

[IndentBlankline]
 IndentBlanklineContextChar = 'base03'
 IndentBlanklineContextStart = '- - u'
 IndentBlanklineChar = 'base03'
 IndentBlanklineSpaceChar = 'base03'
 IndentBlanklineSpaceCharBlankline = 'base03'

[Cmp]
 CmpItemAbbrDeprecated = 'base0F - s'
 CmpItemAbbrMatch = 'base0C'
 CmpItemAbbrMatchFuzzy = 'base0C'
 CmpItemKindFunction = 'link:Function'
 CmpItemKindMethod = 'link:TSMethod'
 CmpItemKindConstructor = 'link:TSConstructor'
 CmpItemKindClass = 'link:Type'
 CmpItemKindEnum = 'link:Type'
 CmpItemKindEvent = 'base05'
 CmpItemKindInterface = 'link:Type'
 CmpItemKindStruct = 'link:Structure'
 CmpItemKindVariable = 'link:Variable'
 CmpItemKindField = 'link:TSField'
 CmpItemKindProperty = 'link:TSProperty'
 CmpItemKindEnumMember = 'r3d'
 CmpItemKindConstant = 'link:Constant'
 CmpItemKindKeyword = 'link:Keyword'
 CmpItemKindModule = 'r3d'
 CmpItemKindValue = 'link:Number'
 CmpItemKindUnit = 'base05'
 CmpItemKindText = 'link:TSText'
 CmpItemKindSnippet = 'base08'
 CmpItemKindFile = 'r3d'
 CmpItemKindFolder = 'base05'
 CmpItemKindColor = 'base05'
 CmpItemKindReference = 'r3d'
 CmpItemKindOperator = 'link:Operator'
 CmpItemKindTypeParameter = 'link:TSParameter'

[Custom]
 "@type.java" = 'link:Function'
 "@parameter.doxygen" = 'link:Function'
 "@attribute" = 'link:TSAttribute'
 "@function.builtin" = 'link:TSFuncBuiltin'
 "@tag.delimiter" = 'link:Delimiter'
 "@type.qualifier" = 'link:Keyword'
 "@constructor" = 'link:TSConstructor'
 "@variable.builtin" = 'link:TSVariableBuiltin'
 "@label.json" = 'link:Identifier'
 "@text.literal.ledger" = 'link:Identifier'

