[information]
 name = "florence"
 background = "dark"
 author = 'Felipe Nakamoto <felipe.ymn@gmail.com>'

[palette]
 fg = '#f5f5f5'
 bg = '#0c0e0f'
 alt_fg = '#f5f5f5'
 alt_bg = '#592c1c'
 # dark = '#040604'
 dark = '#14171a'

 search_blue = '#083C5A'
 indent_blankline = '#202020'
 gray = '#404040'
 light_gray = '#d9d9d9'
 blue = '#9FCDD9'
 light_blue = '#E0FCF2'
 cyan = '#78BEAB'
 green = '#9BB02E'
 red = '#D9573D' 
 light_red = '#FFA4CB'
 purple = '#bd658a'
 yellow = '#d4ae5c'
 magenta = '#59223C'
 orange = '#e68147'

 cursor_fg = '#515052'
 cursor_bg = '#AEAFAD'

 sign_add = '#3eb05a'
 sign_change = '#B09435'
 sign_delete = '#B02C34'

 error_red = '#b14f56'
 warning_yellow = '#ab8b46'
 info_blue = '#286180'
 hint_cyan = '#78beab'

 fuzzy_match = '#A3E27C'

 base01 = '#101317'
 base02 = '#1a1d21'
 base03 = '#23262a'
 base04 = '#2b2e32'
 base05 = '#323539'
 base06 = '#c5c5c6'
 base07 = '#cbcbcc'
 base08 = '#d4d4d5'
 base09 = '#37d99e'
 base10 = '#f0a988'
 base1A = '#e5d487'
 base1B = '#e87979'
 base1C = '#37d99e'
 base1D = '#5fb0fc'
 base1E = '#c397d8'
 base0F = '#e87979'

[highlights]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'fg bg'
 ModeMsg = 'fg bg'
 MsgSeparator = 'fg bg'
 SpellCap = 'yellow - u'
 SpellLocal = 'green - u'
 SpellRare = 'orange - u'
 NormalNC = 'fg bg'
 Pmenu = 'light_gray alt_bg - - 50'
 PmenuSel = '- magenta'
 PmenuSbar = '- dark'
 PmenuThumb = '- light_gray'
 WildMenu = 'fg search_blue'
 CursorLineNr = 'alt_fg - b'
 Comment = 'gray - i'
 Folded = 'light_gray dark'
 FoldColumn = 'light_gray dark'
 LineNr = 'gray -'
 FloatBorder = 'alt_fg'
 Whitespace = 'bg -'
 VertSplit = 'gray bg'
 CursorLine = '- dark'
 CursorColumn = '- dark'
 ColorColumn = '- dark'
 NormalFloat = '- dark'
 Visual = '- magenta'
 DiffAdd = 'alt_fg sign_add'
 DiffChange = 'alt_fg sign_change u'
 DiffDelete = 'alt_fg sign_delete'
 QuickFixLine = '- search_blue'
 MatchWord = '- - u'
 MatchParen = 'hint_cyan bg u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 Conceal = 'light_gray'
 Directory = 'blue'
 SpecialKey = 'blue - b'
 Title = 'orange - b'
 ErrorMsg = 'error_red bg b'
 Search = 'light_gray search_blue'
 IncSearch = 'magenta light_gray'
 Substitute = 'light_gray magenta'
 MoreMsg = 'purple'
 Question = 'purple'
 EndOfBuffer = '- -'
 NonText = 'bg bg'
 Variable = 'alt_fg'
 String = 'cyan'
 Character = 'purple'
 Constant = 'purple'
 Number = 'green'
 Boolean = 'yellow - b'
 Float = 'green'
 Identifier = 'light_blue'
 Function = 'red'
 Operator = 'fg'
 Type = 'red'
 StorageClass = 'blue'
 Structure = 'light_blue'
 Typedef = 'blue'
 Keyword = 'blue'
 Statement = 'orange'
 Conditional = 'orange'
 Repeat = 'orange'
 Label = 'orange'
 Exception = 'orange'
 Include = 'orange'
 PreProc = 'orange'
 Define = 'orange'
 Macro = 'orange'
 PreCondit = 'orange'
 Special = 'red'
 SpecialChar = 'light_gray'
 Tag = 'yellow'
 Debug = 'red'
 Delimiter = 'gray -'
 SpecialComment = 'gray'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'cyan bg b'
 Todo = 'magenta bg b'
 Error = 'error_red bg b'
 TabLine = 'light_gray orange'
 TabLineSel = '- purple'
 TabLineFill = 'purple purple'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'blue'
 TSAttribute = 'cyan'
 TSConstructor = 'red'
 TSType = 'link:Type'
 TSTypeBuiltin = 'light_red'
 TSConditional = 'link:Conditional'
 TSException = 'link:Exception'
 TSInclude = 'link:Include'
 TSKeywordReturn = 'orange - b'
 TSKeyword = 'link:Keyword'
 TSKeywordFunction = 'link:Keyword'
 TSLabel = 'link:Label'
 TSNamespace = 'cyan'
 TSRepeat = 'link:repeat'
 TSConstant = 'link:Constant'
 TSConstBuiltin = 'link:Constant'
 TSFloat = 'link:Float'
 TSNumber = 'link:Number'
 TSBoolean = 'link:Boolean'
 TSCharacter = 'link:Character'
 TSError = 'link:Error'
 TSFunction = 'link:Function'
 TSFuncBuiltin = 'blue'
 TSMethod = 'blue'
 TSConstMacro = 'purple'
 TSFuncMacro = 'blue'
 TSVariable = 'link:Variable'
 TSVariableBuiltin = 'light_red'
 TSProperty = 'light_blue'
 TSField = 'fg'
 TSParameter = 'light_blue'
 TSParameterReference = 'light_blue'
 TSSymbol = 'light_blue'
 TSText = 'alt_fg'
 TSOperator = 'link:Operator'
 TSPunctDelimiter = 'alt_fg -'
 TSTagDelimiter = 'alt_fg'
 TSTagAttribute = 'red'
 TSPunctBracket = 'orange -'
 TSPunctSpecial = 'orange'
 TSString = 'link:String'
 TSStringRegex = 'green'
 TSStringEscape = 'cyan - b'
 TSTag = 'link:Tag'
 TSEmphasis = '- - i'
 TSUnderline = '- - u'
 TSTitle = 'link:Title'
 TSLiteral = 'purple'
 TSURI = 'blue - u'
 TSKeywordOperator = 'orange'
 TSStructure = 'link:Structure'
 TSStrong = 'blue - b'
 TSQueryLinterError = 'warning_yellow'
 TreesitterContext = '- dark'

[markdown]
 markdownBlockquote = 'green'
 markdownCode = 'purple'
 markdownCodeBlock = 'purple'
 markdownCodeDelimiter = 'purple'
 markdownH1 = 'blue'
 markdownH2 = 'blue'
 markdownH3 = 'blue'
 markdownH4 = 'blue'
 markdownH5 = 'blue'
 markdownH6 = 'blue'
 markdownHeadingDelimiter = 'blue'
 markdownHeadingRule = 'fg - b'
 markdownId = 'orange'
 markdownIdDeclaration = 'blue'
 markdownIdDelimiter = 'light_gray'
 markdownLinkDelimiter = 'light_gray'
 markdownBold = 'blue - b'
 markdownItalic = '- - i'
 markdownBoldItalic = 'yellow - bi'
 markdownListMarker = 'blue'
 markdownOrderedListMarker = 'blue'
 markdownRule = 'light_gray'
 markdownUrl = 'cyan - u'
 markdownLinkText = 'blue'
 markdownFootnote = 'purple'
 markdownFootnoteDefinition = 'purple'
 markdownEscape = 'yellow'

[Whichkey]
 WhichKey = 'orange'
 WhichKeySeperator = 'green'
 WhichKeyGroup = 'blue'
 WhichKeyDesc = 'light_blue'
 WhichKeyFloat = '- dark'

[Git]
 SignAdd = 'sign_add'
 SignChange = 'sign_change'
 SignDelete = 'sign_delete'
 GitSignsAdd = 'sign_add'
 GitSignsChange = 'sign_change'
 GitSignsDelete = 'sign_delete'

[LSP]
 LspDiagnosticsDefaultError = 'error_red'
 LspDiagnosticsDefaultWarning = 'warning_yellow'
 LspDiagnosticsDefaultInformation = 'info_blue'
 LspDiagnosticsDefaultInfo = 'info_blue'
 LspDiagnosticsDefaultHint = 'hint_cyan'
 LspDiagnosticsVirtualTextError = 'error_red'
 LspDiagnosticsVirtualTextWarning = 'warning_yellow'
 LspDiagnosticsVirtualTextInformation = 'info_blue'
 LspDiagnosticsVirtualTextInfo = 'info_blue'
 LspDiagnosticsVirtualTextHint = 'hint_cyan'
 LspDiagnosticsFloatingError = 'error_red'
 LspDiagnosticsFloatingWarning = 'warning_yellow'
 LspDiagnosticsFloatingInformation = 'info_blue'
 LspDiagnosticsFloatingInfo = 'info_blue'
 LspDiagnosticsFloatingHint = 'hint_cyan'

 DiagnosticSignError = 'error_red'
 DiagnosticSignWarning = 'warning_yellow'
 DiagnosticSignWarn = 'warning_yellow'
 DiagnosticSignInformation = 'info_blue'
 DiagnosticSignInfo = 'info_blue'
 DiagnosticSignHint = 'hint_cyan'
#Test
 DiagnosticFloatingError = 'error_red dark'
 DiagnosticFloatingWarn = 'warning_yellow dark'
 DiagnosticFloatingInfo = 'info_blue dark'
 DiagnosticFloatingHint = 'hint_cyan dark'

 DiagnosticError = 'error_red'
 DiagnosticWarn = 'warning_yellow'
 DiagnosticInfo = 'info_blue'
 DiagnosticHint = 'hint_cyan'

 DiagnosticVirtualTextError = 'error_red'
 DiagnosticVirtualTextWarn = 'warning_yellow'
 DiagnosticVirtualTextInfo  = 'info_blue'
 DiagnosticVirtualTextHint = 'hint_cyan'

 DiagnosticUnderlineError= '- - c error_red'
 DiagnosticUnderlineWarn= '- - c warning_yellow'
 DiagnosticUnderlineInfo= '- - c info_blue'
 DiagnosticUnderlineHint= '- - c hint_cyan'


 LspDiagnosticsSignError = 'error_red'
 LspDiagnosticsSignWarning = 'warning_yellow'
 LspDiagnosticsSignInformation = 'info_blue'
 LspDiagnosticsSignInfo = 'info_blue'
 LspDiagnosticsSignHint = 'hint_cyan'

 LspDiagnosticsError = 'error_red'
 LspDiagnosticsWarning = 'warning_yellow'
 LspDiagnosticsInformation = 'info_blue'
 LspDiagnosticsInfo = 'info_blue'
 LspDiagnosticsHint = 'hint_cyan'
 # LspDiagnosticsUnderlineError = 'red red u'
 # LspDiagnosticsUnderlineWarning = 'red red u'
 # LspDiagnosticsUnderlineInformation = 'red red u'
 # LspDiagnosticsUnderlineInfo = '- - u'
 # LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- #2e303b'
 LspReferenceText = '- #2e303b'
 LspReferenceWrite = '- #2e303b'
 LspCodeLens = 'gray - i'
 LspCodeLensSeparator = 'gray - i'

[Telescope] 
 TelescopeSelection = 'alt_fg'
 TelescopeMatching = 'fuzzy_match - b'
 TelescopeBorder = 'alt_fg'

[NvimTree]
 NvimTreeFolderIcon = 'blue'
 NvimTreeIndentMarker = 'light_red dark'
 NvimTreeNormal = 'alt_fg dark'
 NvimTreeVertSplit = 'bg bg'
 WinSeparator = 'bg bg'
 NvimTreeFolderName = 'blue'
 NvimTreeOpenedFolderName = 'blue - bi'
 NvimTreeEmptyFolderName = 'gray - i'
 NvimTreeGitIgnored = 'gray - i'
 NvimTreeImageFile = 'purple'
 NvimTreeSpecialFile = 'green'
 NvimTreeEndOfBuffer = 'dark dark'
 NvimTreeCursorLine = '- magenta'
 NvimTreeGitignoreIcon = 'orange'
 NvimTreeGitStaged = 'sign_add'
 NvimTreeGitNew = 'sign_add'
 NvimTreeGitRenamed = 'sign_add'
 NvimTreeGitDeleted = 'sign_delete'
 NvimTreeGitMerge = 'sign_change'
 NvimTreeGitDirty = 'sign_change'

 NvimTreeSymlink = 'cyan'
 NvimTreeRootFolder = 'fg - b'
 NvimTreeExecFile = '#9FBA89'
# Custom highlight group for NvimTree Title
 NvimTreeTitle = 'alt_fg bg bi'

[Buffer]
 BufferCurrent = 'fg bg'
 BufferCurrentIndex = 'fg bg'
 BufferCurrentMod = 'info_blue bg'
 BufferCurrentSign = 'hint_cyan bg'
 BufferCurrentTarget = 'red bg b'

 BufferVisible = 'fg bg'
 BufferVisibleIndex = 'fg bg'
 BufferVisibleMod = 'info_blue bg'
 BufferVisibleSign = 'gray bg'
 BufferVisibleTarget = 'red bg b'

 BufferInactive = 'gray alt_bg'
 BufferInactiveIndex = 'gray alt_bg'
 BufferInactiveMod = 'info_blue alt_bg'
 BufferInactiveSign = 'gray alt_bg'
 BufferInactiveTarget = 'red alt_bg b'

[IndentBlankline]
 IndentBlanklineContextChar = 'indent_blankline'
 IndentBlanklineContextStart = '- - u'
 IndentBlanklineChar = 'indent_blankline'
 IndentBlanklineSpaceChar = 'blue'
 IndentBlanklineSpaceCharBlankline = 'info_blue'

[Cmp]
 CmpItemAbbrDeprecated = 'gray - s'
 CmpItemAbbrMatch = 'fuzzy_match'
 CmpItemAbbrMatchFuzzy = 'fuzzy_match'
 CmpItemKindFunction = 'link:Function'
 CmpItemKindMethod = 'link:TSMethod'
 CmpItemKindConstructor = 'link:TSConstructor'
 CmpItemKindClass = 'link:Type'
 CmpItemKindEnum = 'link:Type'
 CmpItemKindEvent = 'alt_fg'
 CmpItemKindInterface = 'link:Type'
 CmpItemKindStruct = 'link:Structure'
 CmpItemKindVariable = 'link:Variable'
 CmpItemKindField = 'link:TSField'
 CmpItemKindProperty = 'link:TSProperty'
 CmpItemKindEnumMember = 'purple'
 CmpItemKindConstant = 'link:Constant'
 CmpItemKindKeyword = 'link:Keyword'
 CmpItemKindModule = 'cyan'
 CmpItemKindValue = 'link:Number'
 CmpItemKindUnit = 'fg'
 CmpItemKindText = 'link:TSText'
 CmpItemKindSnippet = 'yellow'
 CmpItemKindFile = 'orange'
 CmpItemKindFolder = 'fg'
 CmpItemKindColor = 'fg'
 CmpItemKindReference = 'orange'
 CmpItemKindOperator = 'link:Operator'
 CmpItemKindTypeParameter = 'link:TSParameter'
